name: Build AirCard-iOS

on:
  workflow_dispatch:

jobs:
  build:
    name: Build AirCard
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Build app
        run: |
          # Автоматически находим .xcodeproj или .xcworkspace
          PROJECT_FILE=$(ls -d *.xcodeproj | head -n 1)
          SCHEME_NAME=$(basename "$PROJECT_FILE" .xcodeproj)
          
          echo "Building project: $PROJECT_FILE with scheme: $SCHEME_NAME"
          
          xcodebuild -project "$PROJECT_FILE" -scheme "$SCHEME_NAME" -sdk iphoneos -configuration Release archive -archivePath build/App.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          
          mkdir -p Payload
          mv build/App.xcarchive/Products/Applications/*.app Payload/
          zip -r AirCard.ipa Payload
          rm -rf Payload build

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AirCard-iOS
          path: AirCard.ipa
